server: "https://localhost:8000"
auth_dir: "."
interval: 30
test_mode: true
exporters:
  os: true
  ipmi: true
  apt: true
  nvme: true
  nvsmi: true
  bmc_fan: true
  ipmicfg_psu: true
log_monitoring:
  enabled: true
  sources: ["dmesg", "journal", "syslog", "vast"]
  severity_filter: "INFO"
  max_lines_per_cycle: 50
log_level: "DEBUG"