services:
  # PORT 9100
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node-exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    hostname: ${HOSTNAME}
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'
  
  # PORT 9200
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.1
    container_name: cadvisor
    restart: unless-stopped
    ports:
      - "9200:9200"
    command:
    - '--publish=9200:9200'
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    privileged: true
    devices:
      - "/dev/kmsg:/dev/kmsg"

  # PORT 9400
  dcgm-exporter:
    image: nvcr.io/nvidia/k8s/dcgm-exporter:3.3.6-3.4.2-ubuntu22.04
    container_name: dcgm-exporter
    ports:
      - "9400:9400"
    cap_add:
      - SYS_ADMIN      
    hostname: ${HOSTNAME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    restart: unless-stopped

  # PORT 9500
  gddr6-metrics-exporter:
    image: alkorolyov/gddr6-metrics-exporter:latest
    privileged: true
    container_name: gddr6-exporter
    restart: unless-stopped
    volumes:
      - "/var/log/syslog:/var/log/syslog:to"
      - "/var/log/package-count.txt:/var/log/package-count.txt:ro"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ports:
      - "9500:9500"      
