# Server binding
host: "0.0.0.0"
port: 8000

# Logging
log_level: "DEBUG"  # INFO or DEBUG

# Data retention (important for disk space)
metrics_days: 1        # Keep metrics for 30 days

# Test mode (use test admin token if no file found)
test_mode: true