# Server binding
host: "0.0.0.0"
port: 8000

# Logging
log_level: "INFO"

# Data retention
metrics_days: 30
logs_days: 7

# File paths - explicit configuration
auth_dir: "/etc/dcmon-server"                      # All security files directory
db_path: "/var/lib/dcmon-server/dcmon.db"          # Database file path

# Behavior controls
test_mode: false                # Require admin token file (no fallback)
use_tls: true                   # Enable HTTPS