# Server binding
host: "127.0.0.1"
port: 8000

# Logging
log_level: "DEBUG"

# Data retention
metrics_days: 1

# File paths - explicit configuration
auth_dir: "."                    # All security files in current directory
db_path: "./dcmon.db"           # Database in current directory

# Behavior controls
test_mode: true                 # Allow consistent dev admin token fallback
use_tls: true                   # Enable HTTPS