services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command:
      - '--storage.tsdb.retention.time=30d'
    volumes:
      - ./prometheus.yml:/prometheus/prometheus.yml
      -./rules.yml:/prometheus/rules.yml
      - prom_data:/prometheus
    restart: unless-stopped

  vastai-exporter:
    image: alkorolyov/vastai-exporter
    container_name: vastai_exporter
    command:
      - "--api-key=..." #Remember to replace this with your vast API Key
    restart: unless-stopped

volumes:
  prom_data:
