global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules.yml"

scrape_configs:
  - job_name: 'vastai_exporter'
    static_configs:
      - targets: ['vastai_exporter:8622']

  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
    metric_relabel_configs:
    - source_labels: [__name__]
      regex: 'prometheus_tsdb_head_series'
      action: keep

  - job_name: "kale"
    static_configs:
      - targets: ["89.79.244.70:9100"]
    metric_relabel_configs:
      - source_labels: [__name__]
        action: keep
        regex: 'node_cpu_seconds_total|node_memory_MemAvailable_bytes|node_memory_MemTotal_bytes|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_disk_read_bytes_total|node_disk_written_bytes_total|node_filesystem_size_bytes|node_md_disks|node_md_state|apt_(.*)|ipmi_(.*)|fail2ban_(.*)|gpu_(.*)|nvme_(.*)'
  
  # - job_name: 'gaia'
  #   static_configs:
  #     - targets: ['195.93.180.195:9100', '195.93.180.195:9200', '195.93.180.195:9400', '195.93.180.195:9500']
  # - job_name: 'kale'
  #   static_configs:
  #     - targets: ['89.79.244.70:9100', '89.79.244.70:9200', '89.79.244.70:9400', '89.79.244.70:9500']
      
      
